services:
    app:
        build:
            context: .
            dockerfile: dev.Dockerfile
            args:
                - APP_ENV=local
        container_name: app
        ports:
            - "8181:8181"
        volumes:
            - .:/app
            - ./docker/8.2/php.ini:/usr/local/etc/php/php.ini
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            APP_ENV: local
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: accounting_go_db
            DB_USERNAME: admin
            DB_PASSWORD: password123
            XDEBUG_MODE: develop,debug
            XDEBUG_CLIENT_HOST: host.docker.internal
            PHP_IDE_CONFIG: serverName=DockerApp
        networks:
            - gulf-auctions
        depends_on:
            - db
    db:
        image: mysql:8.0
        container_name: db
        ports:
            - "3306:3306"
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: accounting_go_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: password123
            MYSQL_ROOT_PASSWORD: rootpassword123
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./db_data:/var/lib/mysql
        networks:
            - gulf-auctions

networks:
    gulf-auctions:
        driver: bridge

volumes:
    db_data:
        driver: local
